[client]
showSidebarNavigation = false

[theme]
primaryColor = "#2E86AB"
secondaryColor = "#A23B72" 
backgroundColor = '#0E1117'
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"  # Fixed: Changed from "Helvetica" to valid option
borderRadius = "8px"
